#pragma once
enum class MoveType
{
	NO_ACTION,
	LEFT_RESIZING,
	RIGHT_RESIZING,
	TOP_RESIZING,
	BOTTOM_RESIZING,
	LEFT_TOP_RESIZING,
	LEFT_BOTTOM_RESIZING,
	RIGHT_TOP_RESIZING,
	RIGHT_BOTTOM_RESIZING,
	MOVING
};